Update python-app-ubuntu.yml
Back up

diff --git a/.github/workflows/python-app-ubuntu.yml b/.github/workflows/python-app-ubuntu.yml
--- a/.github/workflows/python-app-ubuntu.yml
+++ b/.github/workflows/python-app-ubuntu.yml
@@ -50,6 +50,71 @@ jobs:
           source $VENV
           pytest --version
 
+      # Count the number of lines of code (excluding comments and blank lines) using cloc
+
+      - name: Count LoC
+        id: loc
+        run: |
+            lines_of_code=$(cloc src/unit_test_generator.py | tail -n 2 | head -n 1 | awk '{print $NF}')
+            echo "LOC=$lines_of_code" >>  "$GITHUB_OUTPUT"
+
+      - name: Lint with pylint
+        id: pylint
+        continue-on-error: true
+        run: |
+          set +e
+          # stop the build if there are Python syntax errors or undefined names
+
+          chmod +x run_pylint.sh
+          ./run_pylint.sh src/unit_test_generator.py
+          #poetry run pylint src/unit_test_generator.py
+          DATA=$?
+          if [ $DATA -ne 0 ]; then
+            echo "::notice::Pylint recommends changes." && exit $DATA
+          fi
+          #echo "DATA=$DATA" >> "$GITHUB_OUTPUT"
+          #echo "##[set-output name=data;]$($DATA)"
+          #COLOR#$(chmod +x color_picker.sh && ./color_picker.sh 0 100 $DATA)"
+          #echo "COLOR=green" >> "$GITHUB_OUTPUT"
+
+      - name: pylint badge
+        uses: RubbaBoy/BYOB@v1
+        with:
+          NAME: pylint
+          LABEL: 'pylint'
+          STATUS: ${{ steps.pylint.outputs.MSG }}
+          COLOR: ${{ steps.pylint.outputs.COLOR }}
+          GITHUB_TOKEN: ${{ secrets.DDT }}
+
+      - name: Typecheck with mypy
+        id: mypy
+        continue-on-error: true
+        run: |
+          set +e
+          chmod +x get_mypy_pct_errors.sh
+          python3 -m pip install pandas-stubs
+          ./get_mypy_pct_errors.sh src/unit_test_generator.py ${{ steps.loc.outputs.LOC }}
+
+          if [ $? -ne 0 ]; then
+            echo "::notice::mypy found errors." && exit $DATA
+          fi
+
+      - name: mypybadge
+        uses: RubbaBoy/BYOB@v1
+        env:
+          COLOR: ${{ steps.mypy.outputs.COLOR }}
+          DATA: ${{ steps.mypy.outputs.DATA }}
+        with:
+          NAME: mypy
+          LABEL: 'mypy'
+          STATUS: ${{ steps.mypy.outputs.DATA }}   # echo "$DATA" # ${{ steps.mypy.outputs.data }}
+          COLOR: ${{ steps.mypy.outputs.COLOR }} #echo "$COLOR" #${{ steps.mypy.outputs.color }}
+          GITHUB_TOKEN: ${{ secrets.DDT }}
+          REPOSITORY: ${{ github.actor }}/ddt
+          ACTOR: ${{ github.actor }}
+
+
+
       - name: pytest procedural_division
         env:
           PY_COLORS: "1"
@@ -142,67 +207,4 @@ jobs:
           ls -lah htmlcov
           poetry run coverage-badge -o coverage.svg
           poetry run genbadge coverage -i coverage.xml
-
-      # Count the number of lines of code (excluding comments and blank lines) using cloc
-
-      - name: Count LoC
-        id: loc
-        run: |
-            lines_of_code=$(cloc src/unit_test_generator.py | tail -n 2 | head -n 1 | awk '{print $NF}')
-            echo "LOC=$lines_of_code" >>  "$GITHUB_OUTPUT"
-
-      - name: Lint with pylint
-        id: pylint
-        continue-on-error: true
-        run: |
-          set +e
-          # stop the build if there are Python syntax errors or undefined names
-
-          chmod +x run_pylint.sh
-          ./run_pylint.sh src/unit_test_generator.py
-          #poetry run pylint src/unit_test_generator.py
-          DATA=$?
-          if [ $DATA -ne 0 ]; then
-            echo "::notice::Pylint recommends changes." && exit $DATA
-          fi
-          #echo "DATA=$DATA" >> "$GITHUB_OUTPUT"
-          #echo "##[set-output name=data;]$($DATA)"
-          #COLOR#$(chmod +x color_picker.sh && ./color_picker.sh 0 100 $DATA)"
-          #echo "COLOR=green" >> "$GITHUB_OUTPUT"
-
-      - name: pylint badge
-        uses: RubbaBoy/BYOB@v1
-        with:
-          NAME: pylint
-          LABEL: 'pylint'
-          STATUS: ${{ steps.pylint.outputs.MSG }}
-          COLOR: ${{ steps.pylint.outputs.COLOR }}
-          GITHUB_TOKEN: ${{ secrets.DDT }}
-
-      - name: Typecheck with mypy
-        id: mypy
-        continue-on-error: true
-        run: |
-          set +e
-          chmod +x get_mypy_pct_errors.sh
-          python3 -m pip install pandas-stubs
-          ./get_mypy_pct_errors.sh src/unit_test_generator.py ${{ steps.loc.outputs.LOC }}
-
-          if [ $? -ne 0 ]; then
-            echo "::notice::mypy found errors." && exit $DATA
-          fi
-
-      - name: mypybadge
-        uses: RubbaBoy/BYOB@v1
-        env:
-          COLOR: ${{ steps.mypy.outputs.COLOR }}
-          DATA: ${{ steps.mypy.outputs.DATA }}
-        with:
-          NAME: mypy
-          LABEL: 'mypy'
-          STATUS: ${{ steps.mypy.outputs.DATA }}   # echo "$DATA" # ${{ steps.mypy.outputs.data }}
-          COLOR: ${{ steps.mypy.outputs.COLOR }} #echo "$COLOR" #${{ steps.mypy.outputs.color }}
-          GITHUB_TOKEN: ${{ secrets.DDT }}
-          REPOSITORY: ${{ github.actor }}/ddt
-          ACTOR: ${{ github.actor }}
 
