notice rather than debug

diff --git a/.github/workflows/python-app-ubuntu.yml b/.github/workflows/python-app-ubuntu.yml
--- a/.github/workflows/python-app-ubuntu.yml
+++ b/.github/workflows/python-app-ubuntu.yml
@@ -55,7 +55,7 @@ jobs:
           poetry run pylint src/unit_test_generator.py
           PYLINT_RESULT=$?
           if [ $PYLINT_RESULT -ne 0 ]; then
-            echo "::debug::Pylint recommends changes." && exit $PYLINT_RESULT 
+            echo "::notice::Pylint recommends changes." && exit $PYLINT_RESULT 
           fi
 
       - name: Typecheck with mypy
@@ -66,7 +66,7 @@ jobs:
           poetry run mypy unit_test_generator.py
           MYPY_RESULT=$?
           if [ $MYPY_RESULT_RESULT -ne 0 ]; then
-            echo "::debug::mypy found errors." && exit $MYPY_RESULT
+            echo "::notice::mypy found errors." && exit $MYPY_RESULT
           fi
   
       - name: pytest procedural_division
