Update python-app-ubuntu.yml
WIP

diff --git a/.github/workflows/python-app-ubuntu.yml b/.github/workflows/python-app-ubuntu.yml
--- a/.github/workflows/python-app-ubuntu.yml
+++ b/.github/workflows/python-app-ubuntu.yml
@@ -51,15 +51,29 @@ jobs:
 
 
       - name: Lint with pylint
+        id: pylint
         continue-on-error: true
         run: |
           set +e
           # stop the build if there are Python syntax errors or undefined names
           poetry run pylint src/unit_test_generator.py
-          PYLINT_RESULT=$?
-          if [ $PYLINT_RESULT -ne 0 ]; then
-            echo "::notice::Pylint recommends changes." && exit $PYLINT_RESULT
+          DATA=$?
+          if [ $DATA -ne 0 ]; then
+            echo "::notice::Pylint recommends changes." && exit $DATA
           fi
+          echo "DATA=$DATA" >> "$GITHUB_OUTPUT"
+          echo "##[set-output name=data;]$($DATA)"
+          COLOR#$(chmod +x color_picker.sh && ./color_picker.sh 0 100 $DATA)"
+          echo "COLOR=green" >> "$GITHUB_OUTPUT"
+
+      - name: pylint badge
+        uses: RubbaBoy/BYOB@v1
+        with:
+          NAME: pylint
+          LABEL: 'pylint'
+          STATUS: ${{ steps.pylint.outputs.data }}
+          COLOR: ${{ steps.pylint.outputs.color }}
+          GITHUB_TOKEN: ${{ secrets.DDT }}
 
       - name: Typecheck with mypy
         id: mypy
@@ -69,25 +83,25 @@ jobs:
           cd src
           poetry run mypy --version
           poetry run mypy unit_test_generator.py
-          MYPY_RESULT=$?
-          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
-          echo "MYPY_RESULT=$MYPY_RESULT" >> "$GITHUB_OUTPUT"
-          echo "MYPY_RESULT=$MYPY_RESULT"
+          DATA=$?
+          echo "COLOR=green" >> "$GITHUB_OUTPUT"
+          echo "DATA=$DATA" >> "$GITHUB_OUTPUT"
+          echo "DATA=$DATA"
 
-          if [ $MYPY_RESULT -ne 0 ]; then
-            echo "::notice::mypy found errors." && exit $MYPY_RESULT
+          if [ $DATA -ne 0 ]; then
+            echo "::notice::mypy found errors." && exit $DATA
           fi
 
       - name: mypybadge
         uses: RubbaBoy/BYOB@v1
         env:
-          SELECTED_COLOR: ${{ steps.mypy.outputs.SELECTED_COLOR }}
-          MYPY_RESULT: ${{ steps.mypy.outputs.MYPY_RESULT }}
+          COLOR: ${{ steps.mypy.outputs.COLOR }}
+          DATA: ${{ steps.mypy.outputs.DATA }}
         with:
           NAME: mypy
           LABEL: '# of mypy errors'
-          STATUS: ${{ steps.mypy.outputs.MYPY_RESULT }}   # echo "$MYPY_RESULT" # ${{ steps.mypy.outputs.data }}
-          COLOR: ${{ steps.mypy.outputs.SELECTED_COLOR }} #echo "$SELECTED_COLOR" #${{ steps.mypy.outputs.color }}
+          STATUS: ${{ steps.mypy.outputs.DATA }}   # echo "$DATA" # ${{ steps.mypy.outputs.data }}
+          COLOR: ${{ steps.mypy.outputs.COLOR }} #echo "$COLOR" #${{ steps.mypy.outputs.color }}
           GITHUB_TOKEN: ${{ secrets.DDT }}
           REPOSITORY: ${{ github.actor }}/ddt
           ACTOR: ${{ github.actor }}
@@ -155,36 +169,3 @@ jobs:
           ls -lah htmlcov
           poetry run coverage-badge -o coverage.svg
           poetry run genbadge coverage -i coverage.xml
-
-      
-
-      - id: mypy2
-        run: |
-              echo "MYPY_RESULT=$MYPY_RESULT"
-              echo "##[set-output name=data;]$($MYPY_RESULT)"
-              echo "##[set-output name=color;]$(.color_picker 0 100 $MYPY_RESULT)"
-
-      - id: pylint
-        run: |
-              echo "##[set-output name=data;]$($PYLINT_RESULT)"
-              echo "##[set-output name=color;]$(.color_picker 0 100 $MYPY_RESULT)"
-
-      - name: mypybadge
-        uses: RubbaBoy/BYOB@v1
-        with:
-          NAME: mypy
-          LABEL: 'mypy'
-          STATUS: ${{ steps.mypy2.outputs.data }}
-          COLOR: ${{ steps.mypy2.outputs.color }}
-          GITHUB_TOKEN: ${{ secrets.DDT }}
-          REPOSITORY: ${{ github.actor }}/ddt
-          ACTOR: ${{ github.actor }}
-
-      - name: pylint badge
-        uses: RubbaBoy/BYOB@v1
-        with:
-          NAME: pylint
-          LABEL: 'pylint'
-          STATUS: ${{ steps.pylint.outputs.data }}
-          COLOR: ${{ steps.pylint.outputs.color }}
-          GITHUB_TOKEN: ${{ secrets.DDT }}
