Disbale e option

diff --git a/.github/workflows/python-app-ubuntu.yml b/.github/workflows/python-app-ubuntu.yml
--- a/.github/workflows/python-app-ubuntu.yml
+++ b/.github/workflows/python-app-ubuntu.yml
@@ -50,10 +50,11 @@ jobs:
       - name: Lint with pylint
         continue-on-error: true
         run: |
+         set +e
           # stop the build if there are Python syntax errors or undefined names
           PYLINT_RESULT=$(poetry run pylint src/unit_test_generator.py)          
           if [ $PYLINT_RESULT -ne 0 ]; then
-            echo "::error::Pylint recommends changes." && exit 1
+            echo "::error::Pylint recommends changes." && exit $PYLINT_RESULT 
           fi
 
       - name: Typecheck with mypy
